variables:
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
  AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"


stages:
  # - test
  - plan
  - deploy


## Hidden job to share common code
.common:
  image: 
    name: "hashicorp/terraform:0.12.31"
    entrypoint: [""]
  before_script:
    - echo " Terraform with CICD initialized .. "
    - apk update && apk add make
    - echo "from hidden scripts"
    - ls -la
    - make clean


## testing scripts
# test:
#   stage: test
#   image: "python:latest"
#   before_script:
#     - pip install flake8 black
#     - apt-get update && apt-get install make
#     - echo " Finding Errors with flake8 and formatting with black "
#   script:
#     - make test
#   artifacts:
#     paths:
#       - code_errors.txt

## Plan the changes
plan:
  extends: .common
  stage: plan
  script:
    - make plan


################  PREP ACCOUNTS #############################

## Deploy to prep ( blue ) account
deploy-prep-blue:     
  extends: .common
  stage: deploy
  needs:
    - plan
  script:
    - make prep-blue/deploy
  allow_failure: false
  when: manual

## Deploy to prep ( grey ) account
deploy-prep-grey:     
  extends: .common
  stage: deploy
  needs:
    - deploy-prep-blue
  script:
    - make prep-grey/deploy
  allow_failure: false
  when: manual

## Deploy to prep ( yellow ) account
deploy-prep-yellow:     
  extends: .common
  stage: deploy
  needs:
    - deploy-prep-blue
  script:
    - make prep-yellow/deploy
  allow_failure: false
  when: manual

################## PROD ACCOUNTS  #############################

## Deploy to Prod ( blue ) account
deploy-prod-blue:     
  extends: .common
  stage: deploy
  needs:
    - plan
  script:
    - make prod-blue/deploy
  allow_failure: false
  only:
      - master
  when: manual


## Deploy to Prod ( grey ) account
deploy-prod-grey:     
  extends: .common
  stage: deploy
  needs:
    - deploy-prod-blue
  script:
    - make prod-grey/deploy
  allow_failure: false
  only:
      - master
  when: manual


## Deploy to Prod ( yellow ) account
deploy-prod-yellow:     
  extends: .common
  stage: deploy
  needs:
    - deploy-prod-blue
  script:
    - make prod-yellow/deploy
  allow_failure: false
  only:
      - master
  when: manual

  
